In [10]:
import numpy as np
a = [[], []]
b = [[], []]

print("Enter first matrix")
for i in range(2):
    for j in range(2):
        a[i].append(int(input()))
print("Enter second matrix")
for i in range(2):
    for j in range(2):
        b[i].append(int(input()))
a = np.array(a)
b = np.array(b)
print(a)
print(b)

Enter first matrix
1
2
3
4
Enter second matrix
1
2
3
4
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [13]:
a.dot(b)

array([[ 7, 10],
       [15, 22]])

In [14]:
a@b

array([[ 7, 10],
       [15, 22]])

In [16]:
a.T

array([[1, 3],
       [2, 4]])

In [17]:
np.linalg.matrix_rank(a)

2

In [18]:
a.trace()

5

In [19]:
np.linalg.det(a)

-2.0000000000000004

In [21]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [22]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))