In [12]:
import numpy as np
ar=np.arange(0,21)
print(ar)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
np.array([[1,2],[1,2]])

array([[1, 2],
       [1, 2]])

In [5]:
np.greater(5,8)

False

In [6]:
np.greater_equal(10,10)

True

In [8]:
x=9
y=5
np.less_equal(x,y)

False

In [9]:
np.less(10,10)

False

In [30]:
y=np.identity(3,dtype=int)
print(y)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [14]:
ar[(ar>=9)&(ar<=15)]*=-1
print(ar)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [19]:
m=np.zeros((5,5),dtype=int)
print(m)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [20]:
np.fill_diagonal(m,[1,2,3,4,5])

In [21]:
print(m)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [23]:
z=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(z)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [24]:
np.sum(z)

18

In [25]:
np.sum(z,axis=0)

array([3, 6, 9])

In [26]:
np.sum(z,axis=1)

array([6, 6, 6])

In [27]:
np.savetxt("new.txt",z)

In [28]:
f=np.loadtxt("new.txt")
print(f)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [31]:
np.all(z==y)

False

In [32]:
p=np.array_equal(z,y)
if p:
    print("Array equal")
else:
    print("Array not equal")

Array not equal


In [33]:
y[[0,2],:]=y[[2,0],:]
print(y)

[[0 0 1]
 [0 1 0]
 [1 0 0]]


In [34]:
print(y*z)

[[0 0 3]
 [0 2 0]
 [1 0 0]]


In [35]:
np.multiply(y,z)

array([[0, 0, 3],
       [0, 2, 0],
       [1, 0, 0]])